services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-test-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
